# -*- coding: utf-8 -*-
"""MITU22BTCS0223.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xE9dqMbquMd5g2_AXebVsW9wQ2gpWv79
"""

from datetime import datetime, timedelta

def find_latest_absence_streak_manual(data):
    """
    Finds the latest absence streak for each student without using pandas.
    Adheres strictly to the expected output format.

    Args:
        data (list): A list of dictionaries, where each dictionary represents
                      an attendance record.

    Returns:
        list: A list of dictionaries, where each dictionary contains the
              latest absence streak details for a student.
    """

    student_records = {}
    for record in data:
        student_id = record['student_id']
        attendance_date = datetime.strptime(record['attendance_date'], '%Y-%m-%d').date()
        status = record['status']

        if student_id not in student_records:
            student_records[student_id] = []
        student_records[student_id].append((attendance_date, status))

    results = []
    for student_id, records in student_records.items():
        absent_streaks = []
        current_streak = []

        # Sort records by date
        records.sort()

        for date, status in records:
            if status == 'Absent':
                if not current_streak or date == current_streak[-1][0] + timedelta(days=1):
                    current_streak.append((date, status))
                else:
                    absent_streaks.append(current_streak)
                    current_streak = [(date, status)]
            else:
                if current_streak:
                    absent_streaks.append(current_streak)
                    current_streak = []

        if current_streak:
            absent_streaks.append(current_streak)

        # Find the latest streak
        latest_streak = None
        latest_start_date = None

        for streak in absent_streaks:
            if streak:
                start_date = streak[0][0]
                if latest_start_date is None or start_date > latest_same_date:
                    latest_start_date = start_date
                    latest_streak = streak

        if latest_streak:
            results.append({
                'student_id': student_id,
                'absence_start_date': latest_streak[0][0].strftime('%Y-%m-%d'),  # Format date
                'absence_end_date': latest_streak[-1][0].strftime('%Y-%m-%d'), # Format date
                'total_absent_days': len(latest_streak)
            })

    return results

# Attendance data provided
data = [
    {'student_id': 101, 'attendance_date': '2024-03-01', 'status': 'Absent'},
    {'student_id': 101, 'attendance_date': '2024-03-02', 'status': 'Absent'},
    {'student_id': 101, 'attendance_date': '2024-03-03', 'status': 'Absent'},
    {'student_id': 101, 'attendance_date': '2024-03-04', 'status': 'Absent'},
    {'student_id': 101, 'attendance_date': '2024-03-05', 'status': 'Present'},
    {'student_id': 102, 'attendance_date': '2024-03-02', 'status': 'Absent'},
    {'student_id': 102, 'attendance_date': '2024-03-03', 'status': 'Absent'},
    {'student_id': 102, 'attendance_date': '2024-03-04', 'status': 'Absent'},
    {'student_id': 102, 'attendance_date': '2024-03-05', 'status': 'Absent'},
    {'student_id': 103, 'attendance_date': '2024-03-05', 'status': 'Absent'},
    {'student_id': 103, 'attendance_date': '2024-03-06', 'status': 'Absent'},
    {'student_id': 103, 'attendance_date': '2024-03-07', 'status': 'Absent'},
    {'student_id': 103, 'attendance_date': '2024-03-08', 'status': 'Absent'},
    {'student_id': 103, 'attendance_date': '2024-03-09', 'status': 'Absent'},
    {'student_id': 104, 'attendance_date': '2024-03-01', 'status': 'Present'},
    {'student_id': 104, 'attendance_date': '2024-03-02', 'status': 'Present'},
    {'student_id': 104, 'attendance_date': '2024-03-03', 'status': 'Absent'},
    {'student_id': 104, 'attendance_date': '2024-03-04', 'status': 'Present'},
    {'student_id': 104, 'attendance_date': '2024-03-05', 'status': 'Present'},
]

# Find the latest absence streak
result = find_latest_absence_streak_manual(data)

# Print the result in the specified table format
print("student_id | absence_start_date | absence_end_date | total_absent_days")
print("-" * 68)  # Adjust the length based on your needs
for row in result:
    print(f"{row['student_id']:<10} | {row['absence_start_date']:<18} | {row['absence_end_date']:<16} | {row['total_absent_days']:<17}")